### ISSUE TITLE
Let's add .nvm file to work on common node version

### ISSUE THREAD

**Issue by Wokstym** [Wokstym/react-vis-graph-wrapper#13]

**Comment by ZachHaber** [comment]
That sadly won't work well for me. I use windows in general, plus as long as we keep somewhat up to date on node, it shouldn't matter for web applications as long as you can run the tooling.

**Comment by Wokstym** [comment]
When testing storybook i noticed if i switch to node v17 `yarn storybook` crashes with this error, I think we should think about a solution 
https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

**Comment by ZachHaber** [comment]
https://github.com/nodejs/node/issues/40547#issuecomment-973872717
According to this, it seems likely that's an issue with openssl, but there's a pretty straightforward workaround.

I tend not to use odd node versions just because they are more experimental than the even versions.

**Comment by Wokstym** [comment]
Sure, lets close the issue then
