### ISSUE TITLE
Require Prettier for merge?

### ISSUE THREAD

**Issue by ZachHaber** [Wokstym/react-vis-graph-wrapper#3]
There's a prettier config in the package.json, I feel like it should require prettier to be run before merging, also will need a version of prettier installed as a dev dependency.

**Comment by Wokstym** [comment]
https://github.com/Wokstym/react-vis-graph-wrapper/pull/4

**Comment by Wokstym** [comment]
https://github.com/Wokstym/react-vis-graph-wrapper/pull/4
